In [2]:
# Dependencies
import numpy as np
import pandas as pd

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

In [3]:
engine = create_engine("sqlite:///hawaii.sqlite")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [4]:
# Create our session (link) from Python to the DB
session = Session(engine)

## D1: Determine the Summary Statistics for June

In [5]:
# 1. Import the sqlalchemy extract function.
from sqlalchemy import extract

# 2. Write a query that filters the Measurement table to retrieve the temperatures for the month of June. 
june_temps = session.query(Measurement.date,Measurement.tobs)\
       .filter(extract('month',Measurement.date)==6)

In [6]:
#  3. Convert the June temperatures to a list.
june_temps = session.query(Measurement.date,Measurement.tobs)\
    .filter(extract('month',Measurement.date)==6)\
       .all()

In [7]:
# 4. Create a DataFrame from the list of temperatures for the month of June. 
june_df = pd.DataFrame(june_temps)
june_df.rename(columns={'date':'Date', 'tobs':"June Temps"}, inplace=True)

In [8]:
# 5. Calculate and print out the summary statistics for the June temperature DataFrame.
june_df.describe()

        June Temps
count  1700.000000
mean     74.944118
std       3.257417
min      64.000000
25%      73.000000
50%      75.000000
75%      77.000000
max      85.000000

## D2: Determine the Summary Statistics for December

In [9]:
# 6. Write a query that filters the Measurement table to retrieve the temperatures for the month of December.
dec_temps = session.query(Measurement.date,Measurement.tobs)\
       .filter(extract('month',Measurement.date)==12)

In [10]:
# 7. Convert the December temperatures to a list.
dec_temps = session.query(Measurement.date,Measurement.tobs)\
        .filter(extract('month',Measurement.date)==12)\
        .all()

In [11]:
# 8. Create a DataFrame from the list of temperatures for the month of December. 
dec_df = pd.DataFrame(dec_temps)
dec_df.rename(columns={'date':'Date', 'tobs':"December Temps"}, inplace=True)

In [12]:
# 9. Calculate and print out the summary statistics for the Decemeber temperature DataFrame.
dec_df.describe()

       December Temps
count     1517.000000
mean        71.041529
std          3.745920
min         56.000000
25%         69.000000
50%         71.000000
75%         74.000000
max         83.000000

## D3: Additional query #1 for READ.me report

In [13]:
dec_prcp = session.query(Measurement.date,Measurement.prcp)\
       .filter(extract('month',Measurement.date)==12).all()

In [18]:
dec_prcp_df=pd.DataFrame(dec_prcp)
dec_prcp_df.rename(columns={'date':'Date', 'prcp':"Dec. Precipitation"}, inplace=True)

In [19]:
dec_prcp_df.describe()

       Dec. Precipitation
count         1405.000000
mean             0.216819
std              0.541399
min              0.000000
25%              0.000000
50%              0.030000
75%              0.150000
max              6.420000

## D3: Additional query #2 for READ.me report

In [20]:
june_prcp = session.query(Measurement.date,Measurement.prcp)\
       .filter(extract('month',Measurement.date)==6).all()

In [21]:
june_prcp_df=pd.DataFrame(june_prcp)
june_prcp_df.rename(columns={'date':'Date', 'prcp':"June Precipitation"}, inplace=True)

In [22]:
june_prcp_df.describe()

       June Precipitation
count         1574.000000
mean             0.136360
std              0.335731
min              0.000000
25%              0.000000
50%              0.020000
75%              0.120000
max              4.430000

## office hours

In [29]:
sep_prcp = session.query(Measurement.date,Measurement.prcp)\ #how do i know prcp and tobs are in the database?
       .filter(extract('month',Measurement.date)==9).all()

###### Another beneficial query would be running a filter to show the prescipitaion for each month 
#and then getting the statistics for each. This would help really determine the dryest months 
#- which usually means high surfing activity. That query would be run with the following code.

In [30]:
sep_prcp_df=pd.DataFrame(sep_prcp)

In [31]:
sep_prcp_df.describe()

              prcp
count  1379.000000
mean      0.164249
std       0.437928
min       0.000000
25%       0.000000
50%       0.020000
75%       0.150000
max       6.830000

In [35]:
sep_temp = session.query(Measurement.date,Measurement.tobs)\
       .filter(extract('month',Measurement.date)==9).all()

In [36]:
sep_temp_df=pd.DataFrame(sep_temp)

In [37]:
sep_temp_df.describe()

              tobs
count  1480.000000
mean     76.164865
std       3.535178
min      64.000000
25%      74.000000
50%      76.000000
75%      79.000000
max      87.000000

In [53]:
#avera pcpt, group by month
session.query(Measurement.date, func.avg(Measurement.prcp)).\
group_by(Measurement.date).all()
#filter(extract('month',Measurement.date)==9).all()

#session.query(Measurement.date, func.count(Measurement.station)).\
#group_by(Measurement.station).order_by(func.count(Measurement.station).desc()).all()

[('2010-01-01', 0.15142857142857144),
 ('2010-01-02', 0.002857142857142857),
 ('2010-01-03', 0.0),
 ('2010-01-04', 0.0014285714285714286),
 ('2010-01-05', 0.005),
 ('2010-01-06', 0.11600000000000002),
 ('2010-01-07', 0.27499999999999997),
 ('2010-01-08', 0.008571428571428572),
 ('2010-01-09', 0.002857142857142857),
 ('2010-01-10', 0.002857142857142857),
 ('2010-01-11', 0.12571428571428572),
 ('2010-01-12', 0.002857142857142857),
 ('2010-01-13', 0.0033333333333333335),
 ('2010-01-14', 0.0),
 ('2010-01-15', 0.0),
 ('2010-01-16', 0.0),
 ('2010-01-17', 0.0),
 ('2010-01-18', 0.0),
 ('2010-01-19', 0.0),
 ('2010-01-20', 0.0014285714285714286),
 ('2010-01-21', 0.10833333333333334),
 ('2010-01-22', 0.0),
 ('2010-01-23', 0.0),
 ('2010-01-24', 0.0033333333333333335),
 ('2010-01-25', 0.0),
 ('2010-01-26', 0.03571428571428571),
 ('2010-01-27', 0.2285714285714286),
 ('2010-01-28', 0.12166666666666666),
 ('2010-01-29', 0.438),
 ('2010-01-30', 1.4700000000000002),
 ('2010-01-31', 0.36000000000000004),
 ('2010-02-01', 0.008333333333333333),
 ('2010-02-02', 0.01),
 ('2010-02-03', 0.535),
 ('2010-02-04', 0.002857142857142857),
 ('2010-02-05', 0.022857142857142857),
 ('2010-02-06', 0.017142857142857144),
 ('2010-02-07', 0.002),
 ('2010-02-08', 0.0),
 ('2010-02-09', 0.0),
 ('2010-02-10', 0.0),
 ('2010-02-11', 0.0),
 ('2010-02-12', 0.164),
 ('2010-02-13', 0.13),
 ('2010-02-14', 0.004285714285714286),
 ('2010-02-15', 0.0),
 ('2010-02-16', 0.0),
 ('2010-02-17', 0.008571428571428572),
 ('2010-02-18', 0.0),
 ('2010-02-19', 0.13799999999999998),
 ('2010-02-20', 0.23),
 ('2010-02-21', 0.036666666666666674),
 ('2010-02-22', 0.246),
 ('2010-02-23', 0.005),
 ('2010-02-24', 0.0014285714285714286),
 ('2010-02-25', 0.002857142857142857),
 ('2010-02-26', 0.0033333333333333335),
 ('2010-02-27', 0.0075),
 ('2010-02-28', 0.10200000000000001),
 ('2010-03-01', 0.028571428571428574),
 ('2010-03-02', 0.0),
 ('2010-03-03', 0.018571428571428572),
 ('2010-03-04', 0.41857142857142854),
 ('2010-03-05', 0.33142857142857146),
 ('2010-03-06', 0.33625),
 ('2010-03-07', 0.08571428571428572),
 ('2010-03-08', 0.39142857142857146),
 ('2010-03-09', 0.08875),
 ('2010-03-10', 0.13166666666666668),
 ('2010-03-11', 0.19000000000000003),
 ('2010-03-12', 0.03),
 ('2010-03-13', 0.021666666666666667),
 ('2010-03-14', 0.015000000000000001),
 ('2010-03-15', 0.1975),
 ('2010-03-16', 0.6216666666666667),
 ('2010-03-17', 0.32666666666666666),
 ('2010-03-18', 0.3614285714285714),
 ('2010-03-19', 0.06333333333333334),
 ('2010-03-20', 0.03166666666666667),
 ('2010-03-21', 0.15),
 ('2010-03-22', 0.0),
 ('2010-03-23', 0.0014285714285714286),
 ('2010-03-24', 0.021428571428571432),
 ('2010-03-25', 0.11166666666666665),
 ('2010-03-26', 0.18333333333333335),
 ('2010-03-27', 0.004285714285714286),
 ('2010-03-28', 0.008571428571428572),
 ('2010-03-29', 0.02125),
 ('2010-03-30', 0.07875),
 ('2010-03-31', 0.02),
 ('2010-04-01', 0.018571428571428572),
 ('2010-04-02', 0.054285714285714284),
 ('2010-04-03', 0.2885714285714286),
 ('2010-04-04', 0.5800000000000001),
 ('2010-04-05', 0.48875),
 ('2010-04-06', 0.31875000000000003),
 ('2010-04-07', 1.1871428571428573),
 ('2010-04-08', 0.26375),
 ('2010-04-09', 0.20125),
 ('2010-04-10', 0.08857142857142859),
 ('2010-04-11', 0.17142857142857143),
 ('2010-04-12', 0.0071428571428571435),
 ('2010-04-13', 0.16571428571428573),
 ('2010-04-14', 0.037142857142857144),
 ('2010-04-15', 0.0),
 ('2010-04-16', 0.02),
 ('2010-04-17', 0.01375),
 ('2010-04-18', 0.02875),
 ('2010-04-19', 0.002857142857142857),
 ('2010-04-20', 0.15714285714285717),
 ('2010-04-21', 0.06714285714285714),
 ('2010-04-22', 0.09571428571428574),
 ('2010-04-23', 0.09000000000000001),
 ('2010-04-24', 0.045),
 ('2010-04-25', 0.01125),
 ('2010-04-26', 0.0),
 ('2010-04-27', 0.005),
 ('2010-04-28', 0.10285714285714286),
 ('2010-04-29', 0.24833333333333332),
 ('2010-04-30', 0.16714285714285712),
 ('2010-05-01', 0.15625),
 ('2010-05-02', 0.10375),
 ('2010-05-03', 0.6687500000000001),
 ('2010-05-04', 0.06555555555555555),
 ('2010-05-05', 0.007777777777777777),
 ('2010-05-06', 0.0125),
 ('2010-05-07', 0.09),
 ('2010-05-08', 0.025000000000000005),
 ('2010-05-09', 0.03125),
 ('2010-05-10', 0.07222222222222223),
 ('2010-05-11', 0.0175),
 ('2010-05-12', 0.02857142857142857),
 ('2010-05-13', 0.0642857142857143),
 ('2010-05-14', 0.0022222222222222222),
 ('2010-05-15', 0.08571428571428573),
 ('2010-05-16', 0.1357142857142857),
 ('2010-05-17', 0.021249999999999998),
 ('2010-05-18', 0.0),
 ('2010-05-19', 0.0),
 ('2010-05-20', 0.23571428571428574),
 ('2010-05-21', 0.13428571428571429),
 ('2010-05-22', 0.036250000000000004),
 ('2010-05-23', 0.16142857142857145),
 ('2010-05-24', 0.08857142857142856),
 ('2010-05-25', 0.15777777777777777),
 ('2010-05-26', 0.07555555555555556),
 ('2010-05-27', 0.00625),
 ('2010-05-28', 0.0),
 ('2010-05-29', 0.162),
 ('2010-05-30', 0.01),
 ('2010-05-31', 0.01),
 ('2010-06-01', 0.018750000000000003),
 ('2010-06-02', 0.007777777777777778),
 ('2010-06-03', 0.02666666666666667),
 ('2010-06-04', 0.0011111111111111111),
 ('2010-06-05', 0.01125),
 ('2010-06-06', 0.01625),
 ('2010-06-07', 0.09),
 ('2010-06-08', 0.035),
 ('2010-06-09', 0.0),
 ('2010-06-10', 0.0025),
 ('2010-06-11', 0.0),
 ('2010-06-12', 0.004285714285714286),
 ('2010-06-13', 0.01),
 ('2010-06-14', 0.03),
 ('2010-06-15', 0.02),
 ('2010-06-16', 0.0014285714285714286),
 ('2010-06-17', 0.01),
 ('2010-06-18', 0.10125),
 ('2010-06-19', 0.08142857142857143),
 ('2010-06-20', 0.0071428571428571435),
 ('2010-06-21', 0.0014285714285714286),
 ('2010-06-22', 0.002857142857142857),
 ('2010-06-23', 0.01888888888888889),
 ('2010-06-24', 0.07666666666666667),
 ('2010-06-25', 0.17222222222222222),
 ('2010-06-26', 0.27166666666666667),
 ('2010-06-27', 0.10800000000000001),
 ('2010-06-28', 0.056249999999999994),
 ('2010-06-29', 0.027777777777777776),
 ('2010-06-30', 0.09333333333333332),
 ('2010-07-01', 0.0875),
 ('2010-07-02', 0.225),
 ('2010-07-03', 0.49000000000000005),
 ('2010-07-04', 0.145),
 ('2010-07-05', 0.045000000000000005),
 ('2010-07-06', 0.2525),
 ('2010-07-07', 0.21222222222222223),
 ('2010-07-08', 0.15875),
 ('2010-07-09', 0.14625),
 ('2010-07-10', 0.21625),
 ('2010-07-11', 0.056666666666666664),
 ('2010-07-12', 0.041666666666666664),
 ('2010-07-13', 0.09),
 ('2010-07-14', 0.17285714285714285),
 ('2010-07-15', 0.0842857142857143),
 ('2010-07-16', 0.03875),
 ('2010-07-17', 0.11),
 ('2010-07-18', 0.4283333333333334),
 ('2010-07-19', 0.085),
 ('2010-07-20', 0.2571428571428572),
 ('2010-07-21', 0.01375),
 ('2010-07-22', 0.065),
 ('2010-07-23', 0.1757142857142857),
 ('2010-07-24', 0.06499999999999999),
 ('2010-07-25', 0.0),
 ('2010-07-26', 0.0),
 ('2010-07-27', 0.08142857142857142),
 ('2010-07-28', 0.085),
 ('2010-07-29', 0.06),
 ('2010-07-30', 0.05142857142857143),
 ('2010-07-31', 0.03285714285714286),
 ('2010-08-01', 0.18142857142857144),
 ('2010-08-02', 0.27249999999999996),
 ('2010-08-03', 0.11333333333333334),
 ('2010-08-04', 0.3288888888888889),
 ('2010-08-05', 0.23555555555555557),
 ('2010-08-06', 0.07666666666666666),
 ('2010-08-07', 0.07),
 ('2010-08-08', 0.16),
 ('2010-08-09', 0.036250000000000004),
 ('2010-08-10', 0.006666666666666666),
 ('2010-08-11', 0.04666666666666667),
 ('2010-08-12', 0.01625),
 ('2010-08-13', 0.0575),
 ('2010-08-14', 0.0),
 ('2010-08-15', 0.004285714285714286),
 ('2010-08-16', 0.12125),
 ('2010-08-17', 0.1875),
 ('2010-08-18', 0.03333333333333333),
 ('2010-08-19', 0.08777777777777779),
 ('2010-08-20', 0.0375),
 ('2010-08-21', 0.009999999999999998),
 ('2010-08-22', 0.0071428571428571435),
 ('2010-08-23', 0.008749999999999999),
 ('2010-08-24', 0.06125),
 ('2010-08-25', 0.1325),
 ('2010-08-26', 0.11555555555555556),
 ('2010-08-27', 0.21),
 ('2010-08-28', 0.06571428571428571),
 ('2010-08-29', 0.2275),
 ('2010-08-30', 0.051111111111111114),
 ('2010-08-31', 0.05666666666666667),
 ('2010-09-01', 0.02888888888888889),
 ('2010-09-02', 0.125),
 ('2010-09-03', 0.19624999999999998),
 ('2010-09-04', 0.06714285714285714),
 ('2010-09-05', 0.05625),
 ('2010-09-06', 0.06875),
 ('2010-09-07', 0.23888888888888887),
 ('2010-09-08', 0.07),
 ('2010-09-09', 0.01125),
 ('2010-09-10', 0.04666666666666667),
 ('2010-09-11', 0.07714285714285715),
 ('2010-09-12', 0.0014285714285714286),
 ('2010-09-13', 0.0022222222222222222),
 ('2010-09-14', 0.042222222222222223),
 ('2010-09-15', 0.007777777777777778),
 ('2010-09-16', 0.030000000000000002),
 ('2010-09-17', 0.003333333333333333),
 ('2010-09-18', 0.04285714285714286),
 ('2010-09-19', 0.13999999999999999),
 ('2010-09-20', 0.057499999999999996),
 ('2010-09-21', 0.04625),
 ('2010-09-22', 0.24555555555555555),
 ('2010-09-23', 0.36),
 ('2010-09-24', 0.006666666666666666),
 ('2010-09-25', 0.08857142857142856),
 ('2010-09-26', 0.0),
 ('2010-09-27', 0.0025),
 ('2010-09-28', 0.0011111111111111111),
 ('2010-09-29', 0.0),
 ('2010-09-30', 0.35428571428571426),
 ('2010-10-01', 0.7275),
 ('2010-10-02', 0.34625),
 ('2010-10-03', 0.03),
 ('2010-10-04', 0.12222222222222223),
 ('2010-10-05', 0.060000000000000005),
 ('2010-10-06', 0.01888888888888889),
 ('2010-10-07', 0.003333333333333333),
 ('2010-10-08', 0.0011111111111111111),
 ('2010-10-09', 0.0),
 ('2010-10-10', 0.017142857142857144),
 ('2010-10-11', 0.07428571428571429),
 ('2010-10-12', 0.06375),
 ('2010-10-13', 0.0175),
 ('2010-10-14', 0.005714285714285714),
 ('2010-10-15', 0.00125),
 ('2010-10-16', 0.013333333333333334),
 ('2010-10-17', 0.07166666666666667),
 ('2010-10-18', 0.015000000000000001),
 ('2010-10-19', 0.53625),
 ('2010-10-20', 0.0),
 ('2010-10-21', 0.395),
 ('2010-10-22', 0.17124999999999999),
 ('2010-10-23', 0.002857142857142857),
 ('2010-10-24', 0.0),
 ('2010-10-25', 0.0),
 ('2010-10-26', 0.2755555555555556),
 ('2010-10-27', 0.20777777777777778),
 ('2010-10-28', 0.17333333333333334),
 ('2010-10-29', 0.09000000000000001),
 ('2010-10-30', 0.3985714285714286),
 ('2010-10-31', 0.060000000000000005),
 ('2010-11-01', 0.43571428571428567),
 ('2010-11-02', 0.09571428571428571),
 ('2010-11-03', 0.2842857142857143),
 ('2010-11-04', 0.8912500000000001),
 ('2010-11-05', 0.38666666666666666),
 ('2010-11-06', 0.8257142857142856),
 ('2010-11-07', 0.19571428571428573),
 ('2010-11-08', 0.00125),
 ('2010-11-09', 0.005),
 ('2010-11-10', 0.1375),
 ('2010-11-11', 0.024285714285714282),
 ('2010-11-12', 0.0175),
 ('2010-11-13', 0.07428571428571429),
 ('2010-11-14', 0.05833333333333333),
 ('2010-11-15', 0.32),
 ('2010-11-16', 0.09999999999999999),
 ('2010-11-17', 0.00375),
 ('2010-11-18', 0.0),
 ('2010-11-19', 0.24124999999999996),
 ('2010-11-20', 0.008571428571428572),
 ('2010-11-21', 0.02666666666666667),
 ('2010-11-22', 0.0071428571428571435),
 ('2010-11-23', 0.007777777777777778),
 ('2010-11-24', 0.030000000000000002),
 ('2010-11-25', 0.13),
 ('2010-11-26', 0.02),
 ('2010-11-27', 0.028571428571428574),
 ('2010-11-28', 0.4642857142857143),
 ('2010-11-29', 0.14750000000000002),
 ('2010-11-30', 0.058750000000000004),
 ('2010-12-01', 0.565),
 ('2010-12-02', 0.11571428571428573),
 ('2010-12-03', 0.405),
 ('2010-12-04', 0.027142857142857142),
 ('2010-12-05', 0.0),
 ('2010-12-06', 0.0022222222222222222),
 ('2010-12-07', 0.0022222222222222222),
 ('2010-12-08', 0.05333333333333333),
 ('2010-12-09', 0.19),
 ('2010-12-10', 1.9100000000000001),
 ('2010-12-11', 0.715),
 ('2010-12-12', 0.1457142857142857),
 ('2010-12-13', 0.1925),
 ('2010-12-14', 0.022222222222222223),
 ('2010-12-15', 0.011111111111111112),
 ('2010-12-16', 0.005555555555555556),
 ('2010-12-17', 0.0),
 ('2010-12-18', 0.0),
 ('2010-12-19', 2.684285714285714),
 ('2010-12-20', 3.9316666666666666),
 ('2010-12-21', 0.6449999999999999),
 ('2010-12-22', 0.12333333333333335),
 ('2010-12-23', 0.054285714285714284),
 ('2010-12-24', 0.03428571428571429),
 ('2010-12-25', 1.224),
 ('2010-12-26', 1.6420000000000001),
 ('2010-12-27', 0.14142857142857143),
 ('2010-12-28', 0.6428571428571429),
 ('2010-12-29', 0.054285714285714284),
 ('2010-12-30', 0.1142857142857143),
 ('2010-12-31', 0.02428571428571429),
 ('2011-01-01', 0.14857142857142858),
 ('2011-01-02', 0.02142857142857143),
 ('2011-01-03', 0.06714285714285714),
 ('2011-01-04', 0.00625),
 ('2011-01-05', 0.04),
 ('2011-01-06', 0.1275),
 ('2011-01-07', 0.006666666666666666),
 ('2011-01-08', 0.002857142857142857),
 ('2011-01-09', 0.011428571428571429),
 ('2011-01-10', 0.0),
 ('2011-01-11', 0.2866666666666667),
 ('2011-01-12', 0.6414285714285715),
 ('2011-01-13', 4.7942857142857145),
 ('2011-01-14', 0.275),
 ('2011-01-15', 0.008),
 ('2011-01-16', 0.002857142857142857),
 ('2011-01-17', 0.07428571428571429),
 ('2011-01-18', 0.03375),
 ('2011-01-19', 0.04),
 ('2011-01-20', 0.027777777777777776),
 ('2011-01-21', 0.06666666666666667),
 ('2011-01-22', 0.002857142857142857),
 ('2011-01-23', 0.027142857142857142),
 ('2011-01-24', 0.007500000000000001),
 ('2011-01-25', 0.005555555555555556),
 ('2011-01-26', 0.01),
 ('2011-01-27', 0.003333333333333333),
 ('2011-01-28', 0.0044444444444444444),
 ('2011-01-29', 0.03666666666666667),
 ('2011-01-30', 0.0033333333333333335),
 ('2011-01-31', 0.12285714285714287),
 ('2011-02-01', 0.03125),
 ('2011-02-02', 0.00125),
 ('2011-02-03', 0.0),
 ('2011-02-04', 0.0025),
 ('2011-02-05', 0.0),
 ('2011-02-06', 0.051666666666666666),
 ('2011-02-07', 1.1466666666666667),
 ('2011-02-08', 0.8712500000000001),
 ('2011-02-09', 0.002857142857142857),
 ('2011-02-10', 0.08625),
 ('2011-02-11', 0.4575),
 ('2011-02-12', 0.9579999999999999),
 ('2011-02-13', 0.4183333333333334),
 ('2011-02-14', 0.028333333333333335),
 ('2011-02-15', 0.014444444444444446),
 ('2011-02-16', 0.1575),
 ('2011-02-17', 0.030000000000000002),
 ('2011-02-18', 0.0825),
 ('2011-02-19', 0.0),
 ('2011-02-20', 1.8966666666666665),
 ('2011-02-21', 0.004285714285714286),
 ('2011-02-22', 0.15142857142857144),
 ('2011-02-23', 0.023750000000000004),
 ('2011-02-24', 1.2512500000000002),
 ('2011-02-25', 0.00625),
 ('2011-02-26', 0.03833333333333333),
 ('2011-02-27', 0.03166666666666667),
 ('2011-02-28', 0.0033333333333333335),
 ('2011-03-01', 0.0925),
 ('2011-03-02', 0.00125),
 ('2011-03-03', 0.24875),
 ('2011-03-04', 1.16125),
 ('2011-03-05', 0.26),
 ('2011-03-06', 0.55),
 ('2011-03-07', 0.06166666666666667),
 ('2011-03-08', 0.24000000000000002),
 ('2011-03-09', 0.44125),
 ('2011-03-10', 0.8525),
 ('2011-03-11', 0.19000000000000003),
 ('2011-03-12', 0.026666666666666672),
 ('2011-03-13', 0.0033333333333333335),
 ('2011-03-14', 0.0),
 ('2011-03-15', 0.0),
 ('2011-03-16', 0.0014285714285714286),
 ('2011-03-17', 0.060000000000000005),
 ('2011-03-18', 0.06714285714285714),
 ('2011-03-19', 0.1285714285714286),
 ('2011-03-20', 0.2966666666666667),
 ('2011-03-21', 0.0),
 ('2011-03-22', 0.21125),
 ('2011-03-23', 0.07625000000000001),
 ('2011-03-24', 0.30874999999999997),
 ('2011-03-25', 0.04),
 ('2011-03-26', 0.11),
 ('2011-03-27', 0.09333333333333334),
 ('2011-03-28', 0.076),
 ('2011-03-29', 0.041666666666666664),
 ('2011-03-30', 0.03666666666666666),
 ('2011-03-31', 0.0022222222222222222),
 ('2011-04-01', 0.2666666666666667),
 ('2011-04-02', 0.21666666666666665),
 ('2011-04-03', 0.10166666666666667),
 ('2011-04-04', 0.008571428571428572),
 ('2011-04-05', 0.05375),
 ('2011-04-06', 0.09),
 ('2011-04-07', 1.2266666666666666),
 ('2011-04-08', 0.44375),
 ('2011-04-09', 0.075),
 ('2011-04-10', 0.016666666666666666),
 ('2011-04-11', 0.049999999999999996),
 ('2011-04-12', 0.034444444444444444),
 ('2011-04-13', 0.006666666666666666),
 ('2011-04-14', 0.07125),
 ('2011-04-15', 0.024444444444444446),
 ('2011-04-16', 0.16833333333333333),
 ('2011-04-17', 0.0),
 ('2011-04-18', 0.035),
 ('2011-04-19', 0.0022222222222222222),
 ('2011-04-20', 0.00375),
 ('2011-04-21', 0.021111111111111112),
 ('2011-04-22', 0.0),
 ('2011-04-23', 0.005714285714285714),
 ('2011-04-24', 0.01),
 ('2011-04-25', 0.025555555555555557),
 ('2011-04-26', 0.09555555555555556),
 ('2011-04-27', 0.0488888888888889),
 ('2011-04-28', 0.051250000000000004),
 ('2011-04-29', 0.19),
 ('2011-04-30', 0.13166666666666668),
 ('2011-05-01', 0.20666666666666667),
 ('2011-05-02', 0.35833333333333334),
 ('2011-05-03', 1.11625),
 ('2011-05-04', 0.35750000000000004),
 ('2011-05-05', 0.16111111111111112),
 ('2011-05-06', 0.6466666666666666),
 ('2011-05-07', 0.9442857142857143),
 ('2011-05-08', 1.4900000000000002),
 ('2011-05-09', 0.4783333333333333),
 ('2011-05-10', 0.19500000000000003),
 ('2011-05-11', 0.42000000000000004),
 ('2011-05-12', 0.0425),
 ('2011-05-13', 0.05142857142857143),
 ('2011-05-14', 0.01),
 ('2011-05-15', 0.0),
 ('2011-05-16', 0.0025),
 ('2011-05-17', 0.01125),
 ('2011-05-18', 0.21250000000000002),
 ('2011-05-19', 0.045),
 ('2011-05-20', 0.005),
 ('2011-05-21', 0.016666666666666666),
 ('2011-05-22', 0.155),
 ('2011-05-23', 0.045),
 ('2011-05-24', 0.005555555555555556),
 ('2011-05-25', 0.015555555555555557),
 ('2011-05-26', 0.00375),
 ('2011-05-27', 0.06875),
 ('2011-05-28', 0.011666666666666665),
 ('2011-05-29', 0.06333333333333334),
 ('2011-05-30', 0.03166666666666667),
 ('2011-05-31', 0.036250000000000004),
 ('2011-06-01', 0.1842857142857143),
 ('2011-06-02', 0.09625),
 ('2011-06-03', 0.8875000000000001),
 ('2011-06-04', 1.6666666666666667),
 ('2011-06-05', 1.4416666666666664),
 ('2011-06-06', 0.021428571428571432),
 ('2011-06-07', 0.047142857142857146),
 ('2011-06-08', 0.08125),
 ('2011-06-09', 0.023333333333333334),
 ('2011-06-10', 0.025714285714285714),
 ('2011-06-11', 0.035),
 ('2011-06-12', 0.3416666666666666),
 ('2011-06-13', 0.0875),
 ('2011-06-14', 0.04555555555555556),
 ('2011-06-15', 0.008749999999999999),
 ('2011-06-16', 0.17857142857142858),
 ('2011-06-17', 0.03),
 ('2011-06-18', 0.014285714285714287),
 ('2011-06-19', 0.3442857142857143),
 ('2011-06-20', 0.20000000000000004),
 ('2011-06-21', 0.365),
 ('2011-06-22', 0.48124999999999996),
 ('2011-06-23', 0.16285714285714287),
 ('2011-06-24', 0.35428571428571426),
 ('2011-06-25', 0.014285714285714287),
 ('2011-06-26', 0.09333333333333334),
 ('2011-06-27', 0.18833333333333332),
 ('2011-06-28', 0.08857142857142856),
 ('2011-06-29', 0.023333333333333334),
 ('2011-06-30', 0.005),
 ('2011-07-01', 0.04125),
 ('2011-07-02', 0.028333333333333335),
 ('2011-07-03', 0.07833333333333332),
 ('2011-07-04', 0.038571428571428576),
 ('2011-07-05', 0.07428571428571429),
 ('2011-07-06', 0.042499999999999996),
 ('2011-07-07', 0.15999999999999998),
 ('2011-07-08', 0.06333333333333334),
 ('2011-07-09', 0.035),
 ('2011-07-10', 0.021666666666666664),
 ('2011-07-11', 0.03666666666666667),
 ('2011-07-12', 0.002),
 ('2011-07-13', 0.03166666666666667),
 ('2011-07-14', 0.05714285714285715),
 ('2011-07-15', 0.10714285714285714),
 ('2011-07-16', 0.05285714285714286),
 ('2011-07-17', 0.18333333333333335),
 ('2011-07-18', 0.043333333333333335),
 ('2011-07-19', 0.015714285714285715),
 ('2011-07-20', 0.16285714285714284),
 ('2011-07-21', 0.05),
 ('2011-07-22', 0.285),
 ('2011-07-23', 0.03333333333333333),
 ('2011-07-24', 0.06999999999999999),
 ('2011-07-25', 0.13499999999999998),
 ('2011-07-26', 0.048749999999999995),
 ('2011-07-27', 0.37125),
 ('2011-07-28', 0.035),
 ('2011-07-29', 0.1557142857142857),
 ('2011-07-30', 0.385),
 ('2011-07-31', 0.002),
 ('2011-08-01', 0.0014285714285714286),
 ('2011-08-02', 0.054285714285714284),
 ('2011-08-03', 0.0325),
 ('2011-08-04', 0.06285714285714286),
 ('2011-08-05', 0.09571428571428572),
 ('2011-08-06', 0.018333333333333337),
 ('2011-08-07', 0.055714285714285716),
 ('2011-08-08', 0.0014285714285714286),
 ('2011-08-09', 0.2885714285714286),
 ('2011-08-10', 0.006666666666666667),
 ('2011-08-11', 0.03142857142857143),
 ('2011-08-12', 0.012857142857142859),
 ('2011-08-13', 0.02),
 ('2011-08-14', 0.10833333333333334),
 ('2011-08-15', 0.09142857142857143),
 ('2011-08-16', 0.03875000000000001),
 ('2011-08-17', 0.09875),
 ('2011-08-18', 0.03142857142857143),
 ('2011-08-19', 0.03166666666666667),
 ('2011-08-20', 0.1),
 ('2011-08-21', 0.06999999999999999),
 ('2011-08-22', 0.092),
 ('2011-08-23', 0.08857142857142856),
 ('2011-08-24', 0.0475),
 ('2011-08-25', 0.085),
 ('2011-08-26', 0.054285714285714284),
 ('2011-08-27', 0.10714285714285714),
 ('2011-08-28', 0.17333333333333334),

In [ ]:
sep_temp = session.query(Measurement.date,Measurement.tobs)\
       .filter(extract('month',Measurement.date)==9).all()
sep_temp_df=pd.DataFrame(sep_temp)
sep_temp_df.describe()